# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get summoners
# @name getSummonersByNicknameAndTagname
GET {{baseUrl}}/summoners/out of ur misery/br1

###

# Get summoners
# @name getMatchesIdBySummoner
GET {{baseUrl}}/matches/puuid